xv6: xv6/bootmain.c File Reference
xv6/bootmain.c File Reference
#include "types.h"
#include "elf.h"
#include "x86.h"
Defines
#define SECTSIZE 512
Functions
void readseg (uchar *, uint, uint)
void bootmain (void)
void waitdisk (void)
void readsect (void *dst, uint offset)
Define Documentation
#define SECTSIZE 512
Definition at line 12 of file bootmain.c.
Referenced by readsect(), and readseg().
Function Documentation
void bootmain (void)
Definition at line 17 of file bootmain.c.
References elfhdr::elf, ELF_MAGIC, proghdr::filesz, proghdr::memsz, proghdr::offset, readseg(), stosb(), and proghdr::va.
void readsect (void * dst, uint offset)
Definition at line 59 of file bootmain.c.
References insl(), outb(), SECTSIZE, and waitdisk().
Referenced by readseg().
void readseg (uchar * va, uint count, uint offset)
Definition at line 78 of file bootmain.c.
References readsect(), and SECTSIZE.
Referenced by bootmain().
void waitdisk (void)
Definition at line 50 of file bootmain.c.
References inb().
Referenced by readsect().