xv6: xv6/cat.c File Reference
xv6/cat.c File Reference
#include "types.h"
#include "stat.h"
#include "user.h"
Functions
void cat (int fd)
int main (int argc, char *argv[])
Variables
char buf [512]
Function Documentation
void cat (int fd)
Definition at line 8 of file cat.c.
References exit(), printf(), read(), and write().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 21 of file cat.c.
References cat(), close(), exit(), open(), and printf().
Variable Documentation
char buf[512]
Definition at line 5 of file cat.c.