xv6: xv6/console.c File Reference
xv6/console.c File Reference
#include "types.h"
#include "defs.h"
#include "param.h"
#include "traps.h"
#include "spinlock.h"
#include "fs.h"
#include "file.h"
#include "mmu.h"
#include "proc.h"
#include "x86.h"
Defines
#define BACKSPACE 0x100
#define CRTPORT 0x3d4
#define INPUT_BUF 128
#define C(x) ((x)-'@')
Functions
static void consputc (int)
static void printint (int xx, int base, int sgn)
void cprintf (char *fmt,...)
void panic (char *s)
static void cgaputc (int c)
void consoleintr (int(*getc)(void))
int consoleread (struct inode *ip, char *dst, int n)
int consolewrite (struct inode *ip, char *buf, int n)
void consoleinit (void)
Variables
static int panicked = 0
struct {
struct spinlock lock
int locking
} cons
static ushort * crt = (ushort*)0xb8000
struct {
struct spinlock lock
char buf [INPUT_BUF]
uint r
uint w
uint e
} input
Define Documentation
#define BACKSPACE 0x100
Definition at line 119 of file console.c.
Referenced by cgaputc(), and consoleintr().
#define C (x) ((x)-'@')
Definition at line 177 of file console.c.
Referenced by consoleintr(), and consoleread().
#define CRTPORT 0x3d4
Definition at line 120 of file console.c.
Referenced by cgaputc().
#define INPUT_BUF 128
Definition at line 168 of file console.c.
Referenced by consoleintr(), and consoleread().
Function Documentation
static void cgaputc (int c) [static]
Definition at line 124 of file console.c.
References BACKSPACE, crt, CRTPORT, inb(), memmove(), memset(), and outb().
Referenced by consputc().
void consoleinit (void)
Definition at line 272 of file console.c.
References cons, CONSOLE, consoleread(), consolewrite(), initlock(), input, ioapicenable(), IRQ_KBD, and picenable().
Referenced by mpmain().
void consoleintr (int(*)(void) getc)
Definition at line 180 of file console.c.
References acquire(), BACKSPACE, C, consputc(), input, INPUT_BUF, procdump(), release(), and wakeup().
Referenced by kbdintr(), and uartintr().
int consoleread (struct inode * ip, char * dst, int n)
Definition at line 219 of file console.c.
References acquire(), C, ilock(), input, INPUT_BUF, iunlock(), release(), and sleep().
Referenced by consoleinit().
int consolewrite (struct inode * ip, char * buf, int n)
Definition at line 257 of file console.c.
References acquire(), cons, consputc(), ilock(), iunlock(), and release().
Referenced by consoleinit().
void consputc (int c) [static]
Definition at line 156 of file console.c.
References cgaputc(), cli(), panicked, and uartputc().
Referenced by consoleintr(), consolewrite(), cprintf(), and printint().
void cprintf (char * fmt, ...)
Definition at line 51 of file console.c.
References acquire(), cons, consputc(), locking, printint(), and release().
Referenced by cpunum(), ideintr(), ioapicinit(), kalloc(), kinit(), mpinit(), mpmain(), panic(), procdump(), syscall(), and trap().
void panic (char * s)
Definition at line 101 of file console.c.
References cli(), cons, cprintf(), getcallerpcs(), panicked, and spinlock::pcs.
Referenced by acquire(), balloc(), bfree(), bget(), bmap(), brelse(), bwrite(), create(), dirlink(), dirlookup(), exit(), fileclose(), filedup(), fileread(), filewrite(), fork1(), ialloc(), iderw(), idestart(), iget(), ilock(), iput(), isdirempty(), iunlock(), kalloc(), kfree(), mpinit(), parseblock(), parsecmd(), parseexec(), parseredirs(), popcli(), release(), runcmd(), sched(), sleep(), sys_unlink(), and trap().
static void printint (int xx, int base, int sgn) [static]
Definition at line 26 of file console.c.
References consputc().
Referenced by cprintf(), and printf().
Variable Documentation
char buf[INPUT_BUF]
Definition at line 171 of file console.c.
struct { ... } cons [static]
Referenced by consoleinit(), consolewrite(), cprintf(), and panic().
ushort* crt = (ushort*)0xb8000 [static]
Definition at line 121 of file console.c.
Referenced by cgaputc().
uint e
Definition at line 174 of file console.c.
Referenced by mpinit(), and mpsearch1().
struct { ... } input
Referenced by consoleinit(), consoleintr(), and consoleread().
struct spinlock lock [read]
Definition at line 21 of file console.c.
int locking
Definition at line 22 of file console.c.
Referenced by cprintf().
int panicked = 0 [static]
Definition at line 18 of file console.c.
Referenced by consputc(), and panic().
uint r
Definition at line 172 of file console.c.
Referenced by fileread(), filewrite(), idewait(), kalloc(), kfree(), and stat().
uint w
Definition at line 173 of file console.c.
Referenced by wc().