xv6: xv6/exec.c File Reference
xv6/exec.c File Reference
#include "types.h"
#include "param.h"
#include "mmu.h"
#include "proc.h"
#include "defs.h"
#include "x86.h"
#include "elf.h"
Functions
int exec (char *path, char **argv)
Function Documentation
int exec (char * path, char ** argv)
Definition at line 10 of file exec.c.
References ELF_MAGIC, ELF_PROG_LOAD, ilock(), iunlockput(), kalloc(), kfree(), mem(), memmove(), memset(), namei(), PAGE, readi(), safestrcpy(), strlen(), and usegment().
Referenced by exectest(), main(), runcmd(), and sys_exec().