xv6: xv6/forktest.c File Reference
xv6/forktest.c File Reference
#include "types.h"
#include "stat.h"
#include "user.h"
Functions
void printf (int fd, char *s,...)
void forktest (void)
int main (void)
Function Documentation
void forktest (void)
Definition at line 15 of file forktest.c.
References exit(), fork(), printf(), and wait().
Referenced by main().
int main (void)
Definition at line 50 of file forktest.c.
References exit(), and forktest().
void printf (int fd, char * s, ...)
Definition at line 9 of file forktest.c.
Referenced by balloc(), bigdir(), bigfile(), cat(), concreate(), createdelete(), createtest(), dirfile(), dirtest(), exectest(), exitwait(), forktest(), fourteen(), getcmd(), iref(), linktest(), ls(), main(), mem(), opentest(), parsecmd(), pipe1(), preempt(), rmdot(), runcmd(), sharedfd(), subdir(), twofiles(), unlinkread(), wc(), writetest(), and writetest1().