xv6: xv6/init.c File Reference
xv6/init.c File Reference
#include "types.h"
#include "stat.h"
#include "user.h"
#include "fcntl.h"
Functions
int main (void)
Variables
char * argv [] = { "sh", 0 }
Function Documentation
int main (void)
Definition at line 11 of file init.c.
References argv, dup(), exec(), exit(), fork(), mknod(), O_RDWR, open(), printf(), and wait().
Variable Documentation
char* argv[] = { "sh", 0 }
Definition at line 8 of file init.c.
Referenced by main(), and sys_exec().