xv6: xv6/ioapic.c File Reference
xv6/ioapic.c File Reference
#include "types.h"
#include "defs.h"
#include "traps.h"
Data Structures
struct ioapic
Defines
#define IOAPIC 0xFEC00000
#define REG_ID 0x00
#define REG_VER 0x01
#define REG_TABLE 0x10
#define INT_DISABLED 0x00010000
#define INT_LEVEL 0x00008000
#define INT_ACTIVELOW 0x00002000
#define INT_LOGICAL 0x00000800
Functions
static uint ioapicread (int reg)
static void ioapicwrite (int reg, uint data)
void ioapicinit (void)
void ioapicenable (int irq, int cpunum)
Variables
struct ioapic * ioapic
Define Documentation
#define INT_ACTIVELOW 0x00002000
Definition at line 22 of file ioapic.c.
#define INT_DISABLED 0x00010000
Definition at line 20 of file ioapic.c.
Referenced by ioapicinit().
#define INT_LEVEL 0x00008000
Definition at line 21 of file ioapic.c.
#define INT_LOGICAL 0x00000800
Definition at line 23 of file ioapic.c.
#define IOAPIC 0xFEC00000
Definition at line 9 of file ioapic.c.
Referenced by ioapicinit().
#define REG_ID 0x00
Definition at line 11 of file ioapic.c.
Referenced by ioapicinit().
#define REG_TABLE 0x10
Definition at line 13 of file ioapic.c.
Referenced by ioapicenable(), and ioapicinit().
#define REG_VER 0x01
Definition at line 12 of file ioapic.c.
Referenced by ioapicinit().
Function Documentation
void ioapicenable (int irq, int cpunum)
Definition at line 71 of file ioapic.c.
References ioapicwrite(), ismp, REG_TABLE, and T_IRQ0.
Referenced by consoleinit(), ideinit(), and uartinit().
void ioapicinit (void)
Definition at line 49 of file ioapic.c.
References cprintf(), INT_DISABLED, IOAPIC, ioapicid, ioapicread(), ioapicwrite(), ismp, REG_ID, REG_TABLE, REG_VER, and T_IRQ0.
Referenced by mpmain().
static uint ioapicread (int reg) [static]
Definition at line 35 of file ioapic.c.
References ioapic::data, and ioapic::reg.
Referenced by ioapicinit().
static void ioapicwrite (int reg, uint data) [static]
Definition at line 42 of file ioapic.c.
References ioapic::data, and ioapic::reg.
Referenced by ioapicenable(), and ioapicinit().
Variable Documentation
struct ioapic* ioapic
Definition at line 25 of file ioapic.c.