xv6: xv6/kbd.c File Reference
xv6/kbd.c File Reference
#include "types.h"
#include "x86.h"
#include "defs.h"
#include "kbd.h"
Functions
int kbdgetc (void)
void kbdintr (void)
Function Documentation
int kbdgetc (void)
Definition at line 7 of file kbd.c.
References CAPSLOCK, CTL, ctlmap, E0ESC, inb(), KBDATAP, KBS_DIB, KBSTATP, normalmap, SHIFT, shiftcode, shiftmap, and togglecode.
Referenced by kbdintr().
void kbdintr (void)
Definition at line 47 of file kbd.c.
References consoleintr(), and kbdgetc().
Referenced by trap().