xv6: xv6/ls.c File Reference
xv6/ls.c File Reference
#include "types.h"
#include "stat.h"
#include "user.h"
#include "fs.h"
Functions
char * fmtname (char *path)
void ls (char *path)
int main (int argc, char *argv[])
Function Documentation
char* fmtname (char * path)
Definition at line 7 of file ls.c.
References DIRSIZ, memmove(), memset(), and strlen().
Referenced by ls().
void ls (char * path)
Definition at line 26 of file ls.c.
References close(), DIRSIZ, fmtname(), fstat(), stat::ino, dirent::inum, memmove(), dirent::name, open(), printf(), read(), stat::size, stat(), strcpy(), strlen(), T_DIR, T_FILE, and stat::type.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 74 of file ls.c.
References exit(), and ls().