xv6: xv6/main.c File Reference
xv6/main.c File Reference
#include "types.h"
#include "defs.h"
#include "param.h"
#include "mmu.h"
#include "proc.h"
#include "x86.h"
Functions
static void bootothers (void)
static void mpmain (void)
Function Documentation
static void bootothers (void) [static]
Definition at line 58 of file main.c.
References cpu::booted, cpunum(), cpus, cpu::id, kalloc(), KSTACKSIZE, lapicstartap(), memmove(), mpmain(), and ncpu.
Referenced by mpmain().
static void mpmain (void) [static]
Definition at line 9 of file main.c.
References binit(), bootothers(), consoleinit(), cprintf(), cpus, fileinit(), ideinit(), iinit(), ioapicinit(), ismp, kinit(), ksegment(), lapicinit(), mpbcpu(), mpinit(), picinit(), pinit(), timerinit(), tvinit(), uartinit(), and userinit().
Referenced by bootothers().