xv6: xv6/mkfs.c File Reference
xv6/mkfs.c File Reference
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <assert.h>
#include "types.h"
#include "fs.h"
#include "stat.h"
Defines
#define min(a, b) ((a) < (b) ? (a) : (b))
Functions
void balloc (int)
void wsect (uint, void *)
void winode (uint, struct dinode *)
void rinode (uint inum, struct dinode *ip)
void rsect (uint sec, void *buf)
uint ialloc (ushort type)
void iappend (uint inum, void *p, int n)
ushort xshort (ushort x)
uint xint (uint x)
int main (int argc, char *argv[])
uint i2b (uint inum)
Variables
int nblocks = 995
int ninodes = 200
int size = 1024
int fsfd
struct superblock sb
char zeroes [512]
uint freeblock
uint usedblocks
uint bitblocks
uint freeinode = 1
Define Documentation
#define min (a, b) ((a) < (b) ? (a) : (b))
Definition at line 237 of file mkfs.c.
Function Documentation
void balloc (int used)
Definition at line 222 of file mkfs.c.
References bzero(), IPB, ninodes, printf(), and wsect().
uint i2b (uint inum)
Definition at line 162 of file mkfs.c.
References IPB.
Referenced by rinode(), and winode().
uint ialloc (ushort type)
Definition at line 208 of file mkfs.c.
References bzero(), freeinode, dinode::nlink, dinode::size, dinode::type, winode(), xint(), and xshort().
void iappend (uint inum, void * p, int n)
Definition at line 240 of file mkfs.c.
References dinode::addrs, freeblock, MAXFILE, min, NDIRECT, NINDIRECT, rinode(), rsect(), dinode::size, usedblocks, winode(), wsect(), and xint().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 55 of file mkfs.c.
References balloc(), bitblocks, BSIZE, bzero(), close(), DIRSIZ, exit(), freeblock, fsfd, ialloc(), iappend(), dirent::inum, IPB, dirent::name, nblocks, superblock::nblocks, ninodes, superblock::ninodes, O_RDWR, open(), printf(), read(), rinode(), ROOTINO, sb, dinode::size, size, superblock::size, strcpy(), strncpy(), T_DIR, T_FILE, usedblocks, winode(), wsect(), xint(), xshort(), and zeroes.
void rinode (uint inum, struct dinode * ip)
Definition at line 182 of file mkfs.c.
References i2b(), IPB, and rsect().
Referenced by iappend(), and main().
void rsect (uint sec, void * buf)
Definition at line 195 of file mkfs.c.
References exit(), fsfd, and read().
Referenced by iappend(), rinode(), and winode().
void winode (uint inum, struct dinode * ip)
Definition at line 168 of file mkfs.c.
References i2b(), IPB, rsect(), and wsect().
Referenced by ialloc(), iappend(), and main().
void wsect (uint sec, void * buf)
Definition at line 149 of file mkfs.c.
References exit(), fsfd, and write().
Referenced by balloc(), iappend(), main(), and winode().
uint xint (uint x)
Definition at line 43 of file mkfs.c.
Referenced by ialloc(), iappend(), and main().
ushort xshort (ushort x)
Definition at line 33 of file mkfs.c.
Referenced by ialloc(), and main().
Variable Documentation
uint bitblocks
Definition at line 20 of file mkfs.c.
Referenced by main().
uint freeblock
Definition at line 18 of file mkfs.c.
Referenced by iappend(), and main().
uint freeinode = 1
Definition at line 21 of file mkfs.c.
Referenced by ialloc().
int fsfd
Definition at line 15 of file mkfs.c.
Referenced by main(), rsect(), and wsect().
int nblocks = 995
Definition at line 11 of file mkfs.c.
Referenced by main().
int ninodes = 200
Definition at line 12 of file mkfs.c.
Referenced by balloc(), and main().
struct superblock sb
Definition at line 16 of file mkfs.c.
Referenced by main().
int size = 1024
Definition at line 13 of file mkfs.c.
Referenced by main().
uint usedblocks
Definition at line 19 of file mkfs.c.
Referenced by iappend(), and main().
char zeroes[512]
Definition at line 17 of file mkfs.c.
Referenced by main().