xv6: xv6/mp.c File Reference
xv6/mp.c File Reference
#include "types.h"
#include "defs.h"
#include "param.h"
#include "mp.h"
#include "x86.h"
#include "mmu.h"
#include "proc.h"
Functions
int mpbcpu (void)
static uchar sum (uchar *addr, int len)
static struct mp * mpsearch1 (uchar *addr, int len)
static struct mp * mpsearch (void)
static struct mpconf * mpconfig (struct mp **pmp)
void mpinit (void)
Variables
struct cpu cpus [NCPU]
static struct cpu * bcpu
int ismp
int ncpu
uchar ioapicid
Function Documentation
int mpbcpu (void)
Definition at line 20 of file mp.c.
References cpus.
Referenced by mpmain().
static struct mpconf* mpconfig (struct mp ** pmp) [static, read]
Definition at line 79 of file mp.c.
References mpconf::length, memcmp(), mpsearch(), mp::physaddr, sum(), and mpconf::version.
Referenced by mpinit().
void mpinit (void)
Definition at line 98 of file mp.c.
References mpproc::apicid, mpioapic::apicno, cprintf(), cpus, e, mpproc::flags, cpu::id, mp::imcrp, inb(), ioapicid, ismp, lapic, mpconf::lapicaddr, mpconf::length, MPBOOT, MPBUS, mpconfig(), MPIOAPIC, MPIOINTR, MPLINTR, MPPROC, ncpu, outb(), and panic().
Referenced by mpmain().
static struct mp* mpsearch (void) [static, read]
Definition at line 55 of file mp.c.
References mpsearch1().
Referenced by mpconfig().
static struct mp* mpsearch1 (uchar * addr, int len) [static, read]
Definition at line 38 of file mp.c.
References e, and sum().
Referenced by mpsearch().
static uchar sum (uchar * addr, int len) [static]
Definition at line 26 of file mp.c.
Referenced by mpconfig(), and mpsearch1().
Variable Documentation
struct cpu* bcpu [static]
Definition at line 14 of file mp.c.
struct cpu cpus[NCPU]
Definition at line 13 of file mp.c.
Referenced by bootothers(), ksegment(), mpbcpu(), mpinit(), and mpmain().
uchar ioapicid
Definition at line 17 of file mp.c.
Referenced by ioapicinit(), and mpinit().
int ismp
Definition at line 15 of file mp.c.
Referenced by ioapicenable(), ioapicinit(), mpinit(), and mpmain().
int ncpu
Definition at line 16 of file mp.c.
Referenced by bootothers(), ideinit(), and mpinit().