xv6: xv6/picirq.c File Reference
xv6/picirq.c File Reference
#include "types.h"
#include "x86.h"
#include "traps.h"
Defines
#define IO_PIC1 0x20
#define IO_PIC2 0xA0
#define IRQ_SLAVE 2
Functions
static void picsetmask (ushort mask)
void picenable (int irq)
void picinit (void)
Variables
static ushort irqmask = 0xFFFF & ~(1<<IRQ_SLAVE)
Define Documentation
#define IO_PIC1 0x20
Definition at line 8 of file picirq.c.
Referenced by picinit(), and picsetmask().
#define IO_PIC2 0xA0
Definition at line 9 of file picirq.c.
Referenced by picinit(), and picsetmask().
#define IRQ_SLAVE 2
Definition at line 11 of file picirq.c.
Referenced by picinit().
Function Documentation
void picenable (int irq)
Definition at line 26 of file picirq.c.
References irqmask, and picsetmask().
Referenced by consoleinit(), ideinit(), timerinit(), and uartinit().
void picinit (void)
Definition at line 33 of file picirq.c.
References IO_PIC1, IO_PIC2, IRQ_SLAVE, irqmask, outb(), picsetmask(), and T_IRQ0.
Referenced by mpmain().
static void picsetmask (ushort mask) [static]
Definition at line 18 of file picirq.c.
References IO_PIC1, IO_PIC2, irqmask, and outb().
Referenced by picenable(), and picinit().
Variable Documentation
ushort irqmask = 0xFFFF & ~(1<<IRQ_SLAVE) [static]
Definition at line 15 of file picirq.c.
Referenced by picenable(), picinit(), and picsetmask().