xv6: xv6/printf.c File Reference
xv6/printf.c File Reference
#include "types.h"
#include "stat.h"
#include "user.h"
Functions
static void putc (int fd, char c)
static void printint (int fd, int xx, int base, int sgn)
void printf (int fd, char *fmt,...)
Function Documentation
void printf (int fd, char * fmt, ...)
Definition at line 40 of file printf.c.
References printint(), putc(), strlen(), and write().
static void printint (int fd, int xx, int base, int sgn) [static]
Definition at line 12 of file printf.c.
References putc().
static void putc (int fd, char c) [static]
Definition at line 6 of file printf.c.
References write().
Referenced by printf(), and printint().