xv6: xv6/rm.c File Reference
xv6/rm.c File Reference
#include "types.h"
#include "stat.h"
#include "user.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 6 of file rm.c.
References exit(), printf(), and unlink().