xv6: xv6/string.c File Reference
xv6/string.c File Reference
#include "types.h"
#include "x86.h"
Functions
void * memset (void *dst, int c, uint n)
int memcmp (const void *v1, const void *v2, uint n)
void * memmove (void *dst, const void *src, uint n)
void * memcpy (void *dst, const void *src, uint n)
int strncmp (const char *p, const char *q, uint n)
char * strncpy (char *s, const char *t, int n)
char * safestrcpy (char *s, const char *t, int n)
int strlen (const char *s)
Function Documentation
int memcmp (const void * v1, const void * v2, uint n)
Definition at line 12 of file string.c.
Referenced by mpconfig().
void* memcpy (void * dst, const void * src, uint n)
Definition at line 48 of file string.c.
References memmove().
void* memmove (void * dst, const void * src, uint n)
Definition at line 28 of file string.c.
Referenced by bootothers(), cgaputc(), exec(), fmtname(), fork(), grep(), growproc(), ilock(), iupdate(), ls(), memcpy(), readi(), readsb(), skipelem(), userinit(), and writei().
void* memset (void * dst, int c, uint n)
Definition at line 5 of file string.c.
char* safestrcpy (char * s, const char * t, int n)
Definition at line 78 of file string.c.
Referenced by exec(), and userinit().
int strlen (const char * s)
Definition at line 92 of file string.c.
Referenced by exec(), fmtname(), ls(), main(), parsecmd(), and printf().
int strncmp (const char * p, const char * q, uint n)
Definition at line 54 of file string.c.
Referenced by namecmp().
char* strncpy (char * s, const char * t, int n)
Definition at line 64 of file string.c.
Referenced by dirlink(), and main().