xv6: xv6/sysproc.c File Reference
xv6/sysproc.c File Reference
#include "types.h"
#include "x86.h"
#include "defs.h"
#include "param.h"
#include "mmu.h"
#include "proc.h"
Functions
int sys_fork (void)
int sys_exit (void)
int sys_wait (void)
int sys_kill (void)
int sys_getpid (void)
int sys_sbrk (void)
int sys_sleep (void)
Function Documentation
int sys_exit (void)
Definition at line 15 of file sysproc.c.
References exit().
int sys_fork (void)
Definition at line 9 of file sysproc.c.
References fork().
int sys_getpid (void)
Definition at line 38 of file sysproc.c.
int sys_kill (void)
Definition at line 28 of file sysproc.c.
References argint(), and kill().
int sys_sbrk (void)
Definition at line 44 of file sysproc.c.
References argint(), and growproc().
int sys_sleep (void)
Definition at line 58 of file sysproc.c.
References acquire(), argint(), release(), sleep(), ticks, and tickslock.
int sys_wait (void)
Definition at line 22 of file sysproc.c.
References wait().