xv6: xv6/trap.c File Reference
xv6/trap.c File Reference
#include "types.h"
#include "defs.h"
#include "param.h"
#include "mmu.h"
#include "proc.h"
#include "x86.h"
#include "traps.h"
#include "spinlock.h"
Functions
void tvinit (void)
void idtinit (void)
void trap (struct trapframe *tf)
Variables
struct gatedesc idt [256]
uint vectors []
struct spinlock tickslock
int ticks
Function Documentation
void idtinit (void)
Definition at line 29 of file trap.c.
References idt, and lidt().
void trap (struct trapframe * tf)
Definition at line 35 of file trap.c.
References acquire(), cprintf(), trapframe::cs, DPL_USER, trapframe::eip, trapframe::err, exit(), ideintr(), IRQ_COM1, IRQ_IDE, IRQ_KBD, IRQ_SPURIOUS, IRQ_TIMER, kbdintr(), lapiceoi(), panic(), release(), RUNNING, syscall(), T_IRQ0, T_SYSCALL, ticks, tickslock, trapframe::trapno, uartintr(), wakeup(), and yield().
void tvinit (void)
Definition at line 17 of file trap.c.
References DPL_USER, idt, initlock(), SEG_KCODE, SETGATE, T_SYSCALL, tickslock, and vectors.
Referenced by mpmain().
Variable Documentation
struct gatedesc idt[256]
Definition at line 11 of file trap.c.
Referenced by idtinit(), and tvinit().
int ticks
Definition at line 14 of file trap.c.
Referenced by sys_sleep(), and trap().
struct spinlock tickslock
Definition at line 13 of file trap.c.
Referenced by sys_sleep(), trap(), and tvinit().
uint vectors[]
Referenced by tvinit().