xv6: xv6/uart.c File Reference
xv6/uart.c File Reference
#include "types.h"
#include "defs.h"
#include "param.h"
#include "traps.h"
#include "spinlock.h"
#include "fs.h"
#include "file.h"
#include "mmu.h"
#include "proc.h"
#include "x86.h"
Defines
#define COM1 0x3f8
Functions
void uartinit (void)
void uartputc (int c)
static int uartgetc (void)
void uartintr (void)
Variables
static int uart
Define Documentation
#define COM1 0x3f8
Definition at line 14 of file uart.c.
Referenced by uartgetc(), uartinit(), and uartputc().
Function Documentation
static int uartgetc (void) [static]
Definition at line 64 of file uart.c.
References COM1, inb(), and uart.
Referenced by uartintr().
void uartinit (void)
Definition at line 19 of file uart.c.
References COM1, inb(), ioapicenable(), IRQ_COM1, outb(), picenable(), uart, and uartputc().
Referenced by mpmain().
void uartintr (void)
Definition at line 74 of file uart.c.
References consoleintr(), and uartgetc().
Referenced by trap().
void uartputc (int c)
Definition at line 52 of file uart.c.
References COM1, inb(), microdelay(), outb(), and uart.
Referenced by consputc(), and uartinit().
Variable Documentation
int uart [static]
Definition at line 16 of file uart.c.
Referenced by uartgetc(), uartinit(), and uartputc().