xv6: xv6/ulib.c File Reference
xv6/ulib.c File Reference
#include "types.h"
#include "stat.h"
#include "fcntl.h"
#include "user.h"
#include "x86.h"
Functions
char * strcpy (char *s, char *t)
int strcmp (const char *p, const char *q)
uint strlen (char *s)
void * memset (void *dst, int c, uint n)
char * strchr (const char *s, char c)
char * gets (char *buf, int max)
int stat (char *n, struct stat *st)
int atoi (const char *s)
void * memmove (void *vdst, void *vsrc, int n)
void * memcpy (void *dst, const void *src, uint n)
Function Documentation
int atoi (const char * s)
Definition at line 85 of file ulib.c.
Referenced by main().
char* gets (char * buf, int max)
Definition at line 53 of file ulib.c.
References read().
Referenced by getcmd().
void* memcpy (void * dst, const void * src, uint n)
Definition at line 108 of file ulib.c.
References memmove().
void* memmove (void * vdst, void * vsrc, int n)
Definition at line 96 of file ulib.c.
void* memset (void * dst, int c, uint n)
Definition at line 37 of file ulib.c.
References stosb().
Referenced by allocproc(), backcmd(), bigfile(), bzero(), cgaputc(), concreate(), exec(), execcmd(), fmtname(), getcmd(), growproc(), ialloc(), kfree(), listcmd(), pipecmd(), redircmd(), sharedfd(), sys_exec(), sys_unlink(), twofiles(), and userinit().
int stat (char * n, struct stat * st)
Definition at line 71 of file ulib.c.
References close(), fstat(), O_RDONLY, open(), and r.
Referenced by ls().
char* strchr (const char * s, char c)
Definition at line 44 of file ulib.c.
Referenced by gettoken(), grep(), peek(), and wc().
int strcmp (const char * p, const char * q)
Definition at line 19 of file ulib.c.
char* strcpy (char * s, char * t)
Definition at line 8 of file ulib.c.
Referenced by ls(), and main().
uint strlen (char * s)
Definition at line 27 of file ulib.c.