xv6: xv6/user.h File Reference
xv6/user.h File Reference
Functions
int fork (void)
int exit (void) __attribute__((noreturn))
int wait (void)
int pipe (int *)
int write (int, void *, int)
int read (int, void *, int)
int close (int)
int kill (int)
int exec (char *, char **)
int open (char *, int)
int mknod (char *, short, short)
int unlink (char *)
int fstat (int fd, struct stat *)
int link (char *, char *)
int mkdir (char *)
int chdir (char *)
int dup (int)
int getpid ()
char * sbrk (int)
int sleep (int)
int stat (char *, struct stat *)
char * strcpy (char *, char *)
void * memmove (void *, void *, int)
char * strchr (const char *, char c)
int strcmp (const char *, const char *)
void printf (int, char *,...)
char * gets (char *, int max)
uint strlen (char *)
void * memset (void *, int, uint)
void * malloc (uint)
void free (void *)
int atoi (const char *)
Function Documentation
int atoi (const char *)
Definition at line 85 of file ulib.c.
Referenced by main().
int chdir (char *)
Referenced by dirfile(), dirtest(), iref(), main(), rmdot(), and subdir().
int close (int)
Referenced by bigdir(), bigfile(), concreate(), createdelete(), createtest(), dirfile(), fourteen(), iref(), linktest(), ls(), main(), opentest(), pipe1(), preempt(), runcmd(), sharedfd(), stat(), subdir(), twofiles(), unlinkread(), writetest(), and writetest1().
int dup (int)
Referenced by main(), and runcmd().
int exec (char * , char **)
Definition at line 10 of file exec.c.
References ELF_MAGIC, ELF_PROG_LOAD, ilock(), iunlockput(), kalloc(), kfree(), mem(), memmove(), memset(), namei(), PAGE, readi(), safestrcpy(), strlen(), and usegment().
int exit (void)
Definition at line 395 of file proc.c.
References acquire(), fileclose(), iput(), NOFILE, NPROC, panic(), proc::parent, ptable, sched(), proc::state, wakeup1(), and ZOMBIE.
int fork (void)
Definition at line 194 of file proc.c.
References allocproc(), proc::cwd, trapframe::eax, filedup(), idup(), kalloc(), kfree(), proc::kstack, KSTACKSIZE, proc::mem, memmove(), NOFILE, proc::ofile, proc::parent, proc::pid, RUNNABLE, proc::state, proc::sz, proc::tf, and UNUSED.
void free (void *)
Definition at line 25 of file umalloc.c.
References header::ptr, header::s, and header::size.
Referenced by mem(), and morecore().
int fstat (int fd, struct stat *)
Referenced by ls(), and stat().
int getpid ()
char* gets (char * , int max)
Definition at line 53 of file ulib.c.
References read().
Referenced by getcmd().
int kill (int)
Definition at line 372 of file proc.c.
References acquire(), proc::killed, NPROC, proc::pid, ptable, release(), RUNNABLE, SLEEPING, and proc::state.
int link (char * , char *)
Referenced by bigdir(), concreate(), dirfile(), iref(), linktest(), main(), and subdir().
void* malloc (uint)
Definition at line 64 of file umalloc.c.
References morecore(), header::ptr, header::s, and header::size.
Referenced by backcmd(), execcmd(), listcmd(), mem(), pipecmd(), and redircmd().
void* memmove (void * , void * , int)
Definition at line 96 of file ulib.c.
void* memset (void * , int , uint)
Definition at line 5 of file string.c.
References stosb().
int mkdir (char *)
Referenced by dirfile(), dirtest(), fourteen(), iref(), main(), rmdot(), and subdir().
int mknod (char * , short , short)
Referenced by main().
int open (char * , int)
Referenced by bigdir(), bigfile(), concreate(), createdelete(), createtest(), dirfile(), fourteen(), iref(), linktest(), ls(), main(), opentest(), runcmd(), sharedfd(), stat(), subdir(), twofiles(), unlinkread(), writetest(), and writetest1().
int pipe (int *)
Referenced by pipe1(), preempt(), and runcmd().
void printf (int , char * , ...)
Definition at line 9 of file forktest.c.
References printint(), putc(), strlen(), and write().
Referenced by balloc(), bigdir(), bigfile(), cat(), concreate(), createdelete(), createtest(), dirfile(), dirtest(), exectest(), exitwait(), forktest(), fourteen(), getcmd(), iref(), linktest(), ls(), main(), mem(), opentest(), parsecmd(), pipe1(), preempt(), rmdot(), runcmd(), sharedfd(), subdir(), twofiles(), unlinkread(), wc(), writetest(), and writetest1().
int read (int , void * , int)
Referenced by bigfile(), cat(), concreate(), gets(), grep(), linktest(), ls(), main(), pipe1(), preempt(), rsect(), sharedfd(), subdir(), twofiles(), unlinkread(), wc(), writetest(), and writetest1().
char* sbrk (int)
Referenced by morecore().
int sleep (int)
int stat (char * , struct stat *)
Definition at line 71 of file ulib.c.
References close(), fstat(), O_RDONLY, open(), and r.
Referenced by ls().
char* strchr (const char * , char c)
Definition at line 44 of file ulib.c.
Referenced by gettoken(), grep(), peek(), and wc().
int strcmp (const char * , const char *)
Definition at line 19 of file ulib.c.
char* strcpy (char * , char *)
Definition at line 8 of file ulib.c.
Referenced by ls(), and main().
uint strlen (char *)
Definition at line 27 of file ulib.c.
int unlink (char *)
Referenced by bigdir(), bigfile(), concreate(), createdelete(), createtest(), dirfile(), dirtest(), iref(), linktest(), main(), rmdot(), sharedfd(), subdir(), twofiles(), unlinkread(), writetest(), and writetest1().
int wait (void)
Definition at line 437 of file proc.c.
References acquire(), kfree(), proc::killed, proc::kstack, KSTACKSIZE, proc::mem, proc::name, NPROC, proc::parent, proc::pid, ptable, release(), sleep(), proc::state, proc::sz, UNUSED, and ZOMBIE.
int write (int , void * , int)
Referenced by bigfile(), cat(), dirfile(), grep(), linktest(), pipe1(), preempt(), printf(), putc(), sharedfd(), subdir(), twofiles(), unlinkread(), writetest(), writetest1(), and wsect().