xv6: xv6/usertests.c File Reference
xv6/usertests.c File Reference
#include "types.h"
#include "stat.h"
#include "user.h"
#include "fs.h"
#include "fcntl.h"
Functions
void opentest (void)
void writetest (void)
void writetest1 (void)
void createtest (void)
void dirtest (void)
void exectest (void)
void pipe1 (void)
void preempt (void)
void exitwait (void)
void mem (void)
void sharedfd (void)
void twofiles (void)
void createdelete (void)
void unlinkread (void)
void linktest (void)
void concreate (void)
void bigdir (void)
void subdir (void)
void bigfile (void)
void fourteen (void)
void rmdot (void)
void dirfile (void)
void iref (void)
void forktest (void)
int main (int argc, char *argv[])
Variables
char buf [2048]
char name [3]
char * echoargv [] = { "echo", "ALL", "TESTS", "PASSED", 0 }
int stdout = 1
Function Documentation
void bigdir (void)
Definition at line 741 of file usertests.c.
References close(), exit(), link(), name, O_CREATE, open(), printf(), and unlink().
Referenced by main().
void bigfile (void)
Definition at line 966 of file usertests.c.
References close(), exit(), memset(), O_CREATE, O_RDWR, open(), printf(), read(), unlink(), and write().
Referenced by main().
void concreate (void)
Definition at line 654 of file usertests.c.
References close(), exit(), fork(), link(), memset(), name, O_CREATE, O_RDWR, open(), printf(), read(), unlink(), and wait().
Referenced by main().
void createdelete (void)
Definition at line 468 of file usertests.c.
References close(), exit(), fork(), name, O_CREATE, O_RDWR, open(), printf(), unlink(), and wait().
Referenced by main().
void createtest (void)
Definition at line 141 of file usertests.c.
References close(), name, O_CREATE, O_RDWR, open(), printf(), stdout, and unlink().
Referenced by main().
void dirfile (void)
Definition at line 1102 of file usertests.c.
References chdir(), close(), exit(), link(), mkdir(), O_CREATE, O_RDWR, open(), printf(), unlink(), and write().
Referenced by main().
void dirtest (void)
Definition at line 163 of file usertests.c.
References chdir(), exit(), mkdir(), printf(), stdout, and unlink().
void exectest (void)
Definition at line 190 of file usertests.c.
References echoargv, exec(), exit(), printf(), and stdout.
Referenced by main().
void exitwait (void)
Definition at line 299 of file usertests.c.
References exit(), fork(), printf(), and wait().
Referenced by main().
void forktest (void)
Definition at line 1198 of file usertests.c.
References exit(), fork(), printf(), and wait().
void fourteen (void)
Definition at line 1022 of file usertests.c.
References close(), exit(), mkdir(), O_CREATE, open(), and printf().
Referenced by main().
void iref (void)
Definition at line 1162 of file usertests.c.
References chdir(), close(), exit(), link(), mkdir(), O_CREATE, open(), printf(), and unlink().
Referenced by main().
void linktest (void)
Definition at line 591 of file usertests.c.
References close(), exit(), link(), O_CREATE, O_RDWR, open(), printf(), read(), unlink(), and write().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 1233 of file usertests.c.
References bigdir(), bigfile(), close(), concreate(), createdelete(), createtest(), dirfile(), exectest(), exit(), exitwait(), forktest(), fourteen(), iref(), linktest(), mem(), O_CREATE, open(), opentest(), pipe1(), preempt(), printf(), rmdot(), sharedfd(), subdir(), twofiles(), unlinkread(), writetest(), and writetest1().
void mem (void)
Definition at line 322 of file usertests.c.
References exit(), fork(), free(), malloc(), printf(), and wait().
Referenced by exec(), and main().
void opentest (void)
Definition at line 15 of file usertests.c.
References close(), exit(), open(), printf(), and stdout.
Referenced by main().
void pipe1 (void)
Definition at line 202 of file usertests.c.
References close(), exit(), fork(), pipe(), printf(), read(), wait(), and write().
Referenced by main().
void preempt (void)
Definition at line 253 of file usertests.c.
References close(), fork(), kill(), pipe(), printf(), read(), wait(), and write().
Referenced by main().
void rmdot (void)
Definition at line 1063 of file usertests.c.
References chdir(), exit(), mkdir(), printf(), and unlink().
Referenced by main().
void sharedfd (void)
Definition at line 356 of file usertests.c.
References close(), exit(), fork(), memset(), O_CREATE, O_RDWR, open(), printf(), read(), unlink(), wait(), and write().
Referenced by main().
void subdir (void)
Definition at line 783 of file usertests.c.
References chdir(), close(), exit(), link(), mkdir(), O_CREATE, O_RDONLY, O_RDWR, O_WRONLY, open(), printf(), read(), unlink(), and write().
Referenced by main().
void twofiles (void)
Definition at line 405 of file usertests.c.
References close(), exit(), fork(), memset(), O_CREATE, O_RDWR, open(), printf(), read(), unlink(), wait(), and write().
Referenced by main().
void unlinkread (void)
Definition at line 546 of file usertests.c.
References close(), exit(), O_CREATE, O_RDWR, open(), printf(), read(), unlink(), and write().
Referenced by main().
void writetest (void)
Definition at line 35 of file usertests.c.
References close(), exit(), O_CREATE, O_RDONLY, O_RDWR, open(), printf(), read(), stdout, unlink(), and write().
Referenced by main().
void writetest1 (void)
Definition at line 84 of file usertests.c.
References close(), exit(), MAXFILE, O_CREATE, O_RDONLY, O_RDWR, open(), printf(), read(), stdout, unlink(), and write().
Referenced by main().
Variable Documentation
char buf[2048]
Definition at line 7 of file usertests.c.
char* echoargv[] = { "echo", "ALL", "TESTS", "PASSED", 0 }
Definition at line 9 of file usertests.c.
Referenced by exectest().
char name[3]
Definition at line 8 of file usertests.c.
Referenced by bigdir(), concreate(), create(), createdelete(), createtest(), namei(), sys_link(), and sys_unlink().
int stdout = 1
Definition at line 10 of file usertests.c.
Referenced by createtest(), dirtest(), exectest(), opentest(), writetest(), and writetest1().