xv6: xv6/wc.c File Reference
xv6/wc.c File Reference
#include "types.h"
#include "stat.h"
#include "user.h"
Functions
void wc (int fd, char *name)
int main (int argc, char *argv[])
Variables
char buf [512]
Function Documentation
int main (int argc, char * argv[])
Definition at line 36 of file wc.c.
References close(), exit(), open(), printf(), and wc().
void wc (int fd, char * name)
Definition at line 8 of file wc.c.
References exit(), printf(), read(), strchr(), and w.
Referenced by main().
Variable Documentation
char buf[512]
Definition at line 5 of file wc.c.