xv6: xv6/x86.h File Reference
xv6/x86.h File Reference
Data Structures
struct trapframe
Functions
static uchar inb (ushort port)
static void insl (int port, void *addr, int cnt)
static void outb (ushort port, uchar data)
static void outw (ushort port, ushort data)
static void outsl (int port, const void *addr, int cnt)
static void stosb (void *addr, int data, int cnt)
static void lgdt (struct segdesc *p, int size)
static void lidt (struct gatedesc *p, int size)
static void ltr (ushort sel)
static uint readeflags (void)
static uint xchg (volatile uint *addr, uint newval)
static void loadgs (ushort v)
static void cli (void)
static void sti (void)
Function Documentation
static void cli (void) [inline, static]
Definition at line 113 of file x86.h.
Referenced by consputc(), panic(), and pushcli().
static uchar inb (ushort port) [inline, static]
Definition at line 4 of file x86.h.
Referenced by cgaputc(), ideinit(), idewait(), kbdgetc(), mpinit(), uartgetc(), uartinit(), uartputc(), and waitdisk().
static void insl (int port, void * addr, int cnt) [inline, static]
Definition at line 13 of file x86.h.
Referenced by ideintr(), and readsect().
static void lgdt (struct segdesc * p, int size) [inline, static]
Definition at line 54 of file x86.h.
Referenced by ksegment().
static void lidt (struct gatedesc * p, int size) [inline, static]
Definition at line 68 of file x86.h.
Referenced by idtinit().
static void loadgs (ushort v) [inline, static]
Definition at line 107 of file x86.h.
Referenced by ksegment().
static void ltr (ushort sel) [inline, static]
Definition at line 80 of file x86.h.
Referenced by usegment().
static void outb (ushort port, uchar data) [inline, static]
Definition at line 22 of file x86.h.
Referenced by cgaputc(), ideinit(), idestart(), lapicstartap(), mpinit(), picinit(), picsetmask(), readsect(), timerinit(), uartinit(), and uartputc().
static void outsl (int port, const void * addr, int cnt) [inline, static]
Definition at line 34 of file x86.h.
Referenced by idestart().
static void outw (ushort port, ushort data) [inline, static]
Definition at line 28 of file x86.h.
static uint readeflags (void) [inline, static]
Definition at line 86 of file x86.h.
Referenced by cpunum(), popcli(), pushcli(), and sched().
static void sti (void) [inline, static]
Definition at line 119 of file x86.h.
Referenced by popcli(), and scheduler().
static void stosb (void * addr, int data, int cnt) [inline, static]
Definition at line 43 of file x86.h.
Referenced by bootmain(), and memset().
static uint xchg (volatile uint * addr, uint newval) [inline, static]
Definition at line 94 of file x86.h.
Referenced by acquire(), and release().